package com.chemtable.interactive.core.database.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

@Entity(
    tableName = "elements",
    indices = [Index(value = ["symbol"], unique = true), Index(value = ["name"], unique = false)]
)
data class ElementEntity(
    @PrimaryKey @ColumnInfo(name = "atomic_number") val atomicNumber: Int,
    val symbol: String,
    val name: String,
    @ColumnInfo(name = "name_ko") val nameKo: String,
    @ColumnInfo(name = "latin_name") val latinName: String?,
    @ColumnInfo(name = "latin_pronunciation") val latinPronunciation: String?,
    @ColumnInfo(name = "english_pronunciation") val englishPronunciation: String?,
    @ColumnInfo(name = "discovery_year") val discoveryYear: Int?,
    @ColumnInfo(name = "discoverer") val discoverer: String?,
    @ColumnInfo(name = "discovery_country") val discoveryCountry: String?,
    @ColumnInfo(name = "cost_per_100g_usd") val costPer100gUsd: Double?,
    @ColumnInfo(name = "cost_reference_date") val costReferenceDate: String?,
    @ColumnInfo(name = "cas_number") val casNumber: String?,
    @ColumnInfo(name = "pubchem_cid") val pubchemCid: String?,
    @ColumnInfo(name = "rtecs_number") val rtecsNumber: String?,
    @ColumnInfo(name = "proton_count") val protonCount: Int?,
    @ColumnInfo(name = "neutron_count") val neutronCount: Int?,
    @ColumnInfo(name = "electron_count") val electronCount: Int?,
    @ColumnInfo(name = "electron_shells") val electronShells: String?,
    @ColumnInfo(name = "common_ion_charge") val commonIonCharge: String?,
    @ColumnInfo(name = "ionization_potential") val ionizationPotential: Double?,
    @ColumnInfo(name = "ionization_possibility") val ionizationPossibility: String?,
    @ColumnInfo(name = "covalent_radius") val covalentRadius: Double?,
    @ColumnInfo(name = "vdw_radius") val vanDerWaalsRadius: Double?,
    @ColumnInfo(name = "block_name") val block: String?,
    @ColumnInfo(name = "melting_point") val meltingPoint: Double?,
    @ColumnInfo(name = "boiling_point") val boilingPoint: Double?,
    @ColumnInfo(name = "heat_fusion") val heatOfFusion: Double?,
    @ColumnInfo(name = "liquid_density") val liquidDensity: Double?,
    @ColumnInfo(name = "electrical_conductivity") val electricalConductivity: Double?,
    @ColumnInfo(name = "electrical_type") val electricalType: String?,
    val resistivity: Double?,
    @ColumnInfo(name = "superconducting_temp") val superconductingTemperature: Double?,
    val magnetism: String?,
    @ColumnInfo(name = "mag_suscept_volume") val volumeMagneticSusceptibility: Double?,
    @ColumnInfo(name = "mag_suscept_mass") val massMagneticSusceptibility: Double?,
    @ColumnInfo(name = "mag_suscept_molar") val molarMagneticSusceptibility: Double?,
    @ColumnInfo(name = "crystal_structure") val crystalStructure: String?,
    @ColumnInfo(name = "crystal_system") val crystalSystem: String?,
    @ColumnInfo(name = "lattice_a") val latticeA: Double?,
    @ColumnInfo(name = "lattice_b") val latticeB: Double?,
    @ColumnInfo(name = "lattice_c") val latticeC: Double?,
    @ColumnInfo(name = "lattice_alpha") val latticeAlpha: Double?,
    @ColumnInfo(name = "lattice_beta") val latticeBeta: Double?,
    @ColumnInfo(name = "lattice_gamma") val latticeGamma: Double?,
    @ColumnInfo(name = "crystal_habit") val crystalHabit: String?,
    @ColumnInfo(name = "debye_temp") val debyeTemperature: Double?,
    @ColumnInfo(name = "hardness_brinell") val hardnessBrinell: Double?,
    @ColumnInfo(name = "hardness_mohs") val hardnessMohs: Double?,
    @ColumnInfo(name = "hardness_vickers") val hardnessVickers: Double?,
    @ColumnInfo(name = "bulk_modulus") val bulkModulus: Double?,
    @ColumnInfo(name = "young_modulus") val youngModulus: Double?,
    @ColumnInfo(name = "poisson_ratio") val poissonRatio: Double?,
    @ColumnInfo(name = "shear_modulus") val shearModulus: Double?,
    @ColumnInfo(name = "speed_of_sound") val speedOfSound: Double?,
    @ColumnInfo(name = "refractive_index") val refractiveIndex: Double?,
    @ColumnInfo(name = "electron_affinity") val electronAffinity: Double?,
    @ColumnInfo(name = "electrode_potential") val standardElectrodePotential: Double?,
    @ColumnInfo(name = "radioactivity_level") val radioactivityLevel: String?,
    @ColumnInfo(name = "reactivity_level") val reactivityLevel: String?,
    @ColumnInfo(name = "hazard_health") val hazardHealth: Int?,
    @ColumnInfo(name = "hazard_flammability") val hazardFlammability: Int?,
    @ColumnInfo(name = "hazard_reactivity") val hazardReactivity: Int?,
    @ColumnInfo(name = "hazard_special") val hazardSpecial: String?,
    @ColumnInfo(name = "abundance_universe") val abundanceUniverse: Double?,
    @ColumnInfo(name = "abundance_sun") val abundanceSun: Double?,
    @ColumnInfo(name = "abundance_ocean") val abundanceOcean: Double?,
    @ColumnInfo(name = "abundance_human") val abundanceHuman: Double?,
    @ColumnInfo(name = "abundance_crust") val abundanceCrust: Double?,
    @ColumnInfo(name = "abundance_meteorite") val abundanceMeteorite: Double?,
    @ColumnInfo(name = "data_source") val dataSource: String?,
    @ColumnInfo(name = "data_license") val dataLicense: String?,
    @ColumnInfo(name = "data_updated_at") val dataUpdatedAt: String?,
    @ColumnInfo(name = "data_confidence") val dataConfidence: Double?,
    val category: String,
    val state: String,
    @ColumnInfo(name = "electron_cfg") val electronConfiguration: String,
    @ColumnInfo(name = "molar_mass") val molarMass: Double,
    @ColumnInfo(name = "heat_vap") val heatOfVaporization: Double?,
    @ColumnInfo(name = "specific_heat") val specificHeatCapacity: Double?,
    @ColumnInfo(name = "thermal_exp") val thermalExpansionCoefficient: Double?,
    @ColumnInfo(name = "half_life") val halfLife: String?,
    @ColumnInfo(name = "neutron_cs") val neutronCrossSection: Double?,
    val barn: Double?,
    @ColumnInfo(name = "thermal_cond") val thermalConductivity: Double?,
    @ColumnInfo(name = "electro_neg") val electronegativity: Double?,
    @ColumnInfo(name = "atomic_radius") val atomicRadius: Double?,
    val period: Int,
    @ColumnInfo(name = "group_num") val group: Int
)
